from django.urls import path, include
from django.views.decorators.cache import cache_page
from . import views
urlpatterns = [
path('',cache_page(5)(views.home)),
path('park-where-we-do-activity/<str:aname>,<int:id>', views.activity_data, name='activity_data'),
path('facilities-data/<str:aname>,<int:id>', views.facilities_data, name='facilities_data'),
path('park-detail/<int:id>', cache_page(0)(views.park_detail)),
path('save-park', views.save_park, name='save_park'),
path('trending', views.trending, name='trending'),
path('message', views.message, name='message'),
path('feedback', views.feedback, name='feedback'),
path('faq', views.faq, name='faq'),
path('signin', views.signin, name='signin'),
path('signup', views.signup, name='signup'),
path('covid', views.covid, name='covid'),
path('virtual/<int:id>', views.virtual, name='virtual'),
path('virtual_list', views.virtual_list, name='virtual_list'),
path('nearby/<str:lat>,<str:lon>', views.nearby, name='nearby'),
path('usa_all_park', views.usa_all_park, name='usa_all_park'),
path('state_park/<str:id>', views.state_park, name='state_park'),
path('us_national_park/<str:id>', views.us_national_park, name='us_national_park'),
path('us_national_state/<str:id>', views.us_national_state, name='us_national_state'),
path('us_national_details/<str:id>', views.us_national_details, name='us_national_details'),
path('us_national_alpha/<str:id>', views.us_national_alpha, name='us_national_alpha'),
path('by_country', views.by_country, name='by_country'),
path('country_alphabet_in',views.country_alphabet_in, name='country_alphabet_in'),
path('logout1', views.logout1, name='logout1'),
path('review', views.review, name='review'),
path('wishlist', views.wishlist, name='wishlist'),
path('wishlist_delete', views.wishlist_delete, name='wishlist_delete'),
path('after_review/<str:tag>,<str:id>', views.after_review, name='after_review'),
path('wish_detail/<int:id>', views.wish_detail, name='wish_detail'),
path('wish_detail1/<int:id>', views.wish_detail1, name='wish_detail1'),
path('res_sidebar', views.res_sidebar, name='res_sidebar'),
path('news', views.google_news, name='google_news'),
path('search/<str:s>', cache_page(5)(views.search), name='search'),
path('google_news_api/<str:park_city>',cache_page(0)(views.google_news_api)),
path('google_news_api1/<int:id>',cache_page(0)(views.google_news_api1)),
path('park_hotel_api/<str:p_id>',cache_page(0)(views.park_hotel)),
path('park_hotel_api_search/<str:p_id>', views.park_hotel_search, name='park_hotel_search'),
path('nav', views.nav),
path('reviewcache', views.reviewcache),
path('nearclick', views.nearclick),
path('cweather/<str:city>', cache_page(300)(views.cweather)),
path('hotel_delete_api', views.hotel_delete_api),
path('insert_scraping', views.insert_scraping),
path('insert_scraping_des', views.insert_scraping_des),
path('all_usa_park_detail/<int:id>', views.scraping_park_detail),
path('usa_city_update/<str:ct>', views.usa_city_update),
path('sreview', views.sreview),
path('update_city/<str:nm>', views.update_city),
path('add-location', views.addlocation),
path('park-detail_user/<int:id>', cache_page(0)(views.park_detail_user)),
path('tag_parks/<str:tag>', views.tag_parks),
path('load_review', views.load_review),
path('best-park-in-usa/<str:park_name>,<int:id>', views.scraping_park_detail),
path('hotel-and-news-for-city', views.global_search),
path('demo',cache_page(5)(views.demo)),
path('foodie-find',views.foodie_find),
path('food-camping',views.food_camping),
path('terms-and-conditions',views.terms_conditions),
path('licences',views.licences),
path('Privacy-Policy',views.privacy_policy),
path('community',views.community),
path('home_virtual_list/',cache_page(0)(views.home_virtual_list)),
path('home_activity_list/',cache_page(10)(views.home_activity_list)),
path('home_facility_list/',cache_page(0)(views.home_facility_list)),
path('home_tag_list/',cache_page(10)(views.home_tag_list)),
path('slider_l/',cache_page(60)(views.slider_l)),
path('slider_m/',cache_page(60)(views.slider_m)),




]
