# Generated by Django 2.2.4 on 2021-06-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0013_park_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
