# Generated by Django 2.2.4 on 2021-06-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0014_activities_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
