# Generated by Django 2.2.4 on 2021-08-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0016_guideline_guideline_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline_detail',
            name='typ',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='guideline_detail',
            name='guideline',
            field=models.CharField(max_length=350),
        ),
    ]
