# Generated by Django 2.2.4 on 2021-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0017_auto_20210802_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline_detail',
            name='guide_detail1',
            field=models.CharField(max_length=650),
        ),
        migrations.AlterField(
            model_name='guideline_detail',
            name='guide_detail2',
            field=models.CharField(max_length=650),
        ),
        migrations.AlterField(
            model_name='guideline_detail',
            name='guide_detail3',
            field=models.CharField(max_length=650),
        ),
    ]
