# Generated by Django 2.2.4 on 2021-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0018_auto_20210823_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='park_list_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='none', max_length=800)),
                ('link', models.CharField(default='none', max_length=800)),
                ('tag', models.CharField(default='none', max_length=200)),
                ('state', models.CharField(default='none', max_length=100)),
                ('imagelinks', models.CharField(default='none', max_length=1000)),
            ],
        ),
    ]
