# Generated by Django 2.2.4 on 2021-11-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usa_state_park_list',
            name='image_filter',
        ),
    ]
